cafeteria/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views 

urlpatterns = [
    
    #===========================================
    #              SOLICITUDES
    #===========================================
    path('',views.index, name='tienda'),
    path('solicitudes/', views.solicitud_list, name='solicitud_list'),
    path('solicitudes/entregar/<int:solicitud_id>/', views.entregar_solicitud, name='entregar_solicitud'),
    
    #===========================================
    #              PRODUCTOS
    #===========================================
    path('productos/', views.producto_list, name='producto_list'),
    path('productos/<int:pk>/', views.producto_detail, name='producto_detail'),
    path('productos/nuevo/', views.producto_create, name='producto_create'),
    path('productos/<int:pk>/editar/', views.producto_update, name='producto_update'),
    #path('productos/<int:pk>/eliminar/', views.producto_delete, name='producto_delete'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView , LogoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cafeteria.urls')),
    path('users/',include('customerUser.urls')),
    
    
    
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='tienda'), name='logout'),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafeteria/models.py
from django.db import models
from customerUser.models import CustomUser

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='productos/')
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class SolicitudProducto(models.Model):
    nombre_cliente = models.CharField(max_length=200)
    cantidad = models.IntegerField(default=1)
    mensaje = models.TextField(blank=True, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Solicitud de {self.nombre_cliente} para {self.producto.nombre}"
    
    def total(self):
        return self.cantidad * self.producto.precio

cafeteria/forms.py
# forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'descripcion', 'imagen', 'status']

cafeteria/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto, SolicitudProducto
from customerUser.models import CustomUser
from .forms import ProductoForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

#===========================================
#              SOLICITUDES
#===========================================
def index(request):
    if request.method == 'POST':
        print("Entrando a la solicitud")
        #print("Solicitud recibida:", request.POST)
        
        # Recibir los datos del formulario
        nombre_cliente = request.POST.get('nombre')
        cantidad = request.POST.get('cantidad')
        mensaje = request.POST.get('mensaje', '')
        producto = request.POST.get('producto')
        modelProducto = Producto.objects.get(id=producto)
        #print("Solicitud recibida: ID", producto)
        #return redirect('tienda')

        # Crear y guardar la solicitud
        solicitud = SolicitudProducto(
            nombre_cliente=nombre_cliente,
            cantidad=cantidad,
            mensaje=mensaje,
            producto=modelProducto
        )

        # Si el usuario está autenticado, asociar el usuario a la solicitud
        if request.user.is_authenticated:
            pass
             #request.user
        solicitud.user = CustomUser.objects.get(id=1)
        
        solicitud.save()  # Guardar la solicitud

        # Mostrar mensaje de éxito
        messages.success(request, 'Tu solicitud ha sido registrada exitosamente.')

        # Redirigir al usuario a la lista de solicitudes o alguna otra página
        return redirect('tienda')

    productos = Producto.objects.filter(status=True)
    return render(request, 'tienda/index.html',{'productos': productos})

@login_required
def solicitud_list(request):
    
    #solicitudes = SolicitudProducto.objects.filter(user=request.user)
    solicitudes = SolicitudProducto.objects.filter(user=request.user).order_by('status', 'created')
    #solicitudes = SolicitudProducto.objects.filter(user=request.user).order_by('status', '-created')


    return render(request, 'solicitudes/index.html', {'solicitudes': solicitudes})
@login_required
def entregar_solicitud(request, solicitud_id):
    # Obtener la solicitud por su ID
    solicitud = get_object_or_404(SolicitudProducto, id=solicitud_id)
    
    # Realiza las acciones necesarias para marcar la solicitud como entregada, por ejemplo:
    solicitud.status = False  # O lo que represente "entregada" en tu modelo
    solicitud.save()
    
    # Redirige a la lista de solicitudes
    return redirect('solicitud_list')  # O la URL que desees





#===========================================
#              PRODUCTOS
#===========================================
# Vista para listar productos
@login_required
def producto_list(request):
    
    
    # Si no es una solicitud POST, solo mostrar la página con el producto
    productos = Producto.objects.all()
    return render(request, 'productos/index.html', {'productos': productos})

# Vista para detalle de un producto
@login_required
def producto_detail(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    return render(request, 'productos/view.html', {'producto': producto})

# Vista para crear un producto
@login_required
def producto_create(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('producto_list')
    else:
        form = ProductoForm()
    return render(request, 'productos/form.html', {'form': form})

# Vista para actualizar un producto
@login_required
def producto_update(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('producto_list')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'productos/form.html', {'form': form})

# Vista para eliminar un producto
@login_required
def producto_delete(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        producto.delete()
        return redirect('producto_list')
    return render(request, 'producto_confirm_delete.html', {'producto': producto})


    

cafeteria/templates/productos/form.html
{# templates/product_form.html #}
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="form-card mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card mx-auto shadow-sm" style="max-width: auto;">
                <div class="card-header text-center" style="background-color: #d6a167; color: white;">
                    <h4 class="mb-0">
                        {% if form.instance.pk %}Editar{% else %}Crear{% endif %} Producto
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="row ">
                            <div class="col-md-2"></div>
                            <div class="col-md-4">
                                <!-- Botones de acción -->
                                <button type="submit" class="btn btn-primary w-100"
                                    style="background-color: #d6a167; border-color: #d6a167;">
                                    {% if form.instance.pk %}Actualizar{% else %}Crear{% endif %}
                                </button>

                            </div>
                            <div class="col-md-4">
                                <a href="{% url 'producto_list' %}" class="btn w-100 mt-2"
                                    style="background-color: #bbb; color: #333;">
                                    Cancelar
                                </a>
                            </div>
                        </div>

                        <div class="row my-3">
                            <!-- Nombre -->
                            <div class="form-group mb-3 col-md-6">
                                <label for="id_nombre">Nombre</label>
                                {{ form.nombre|add_class:"form-control" }}
                            </div>

                            <!-- Precio -->
                            <div class="form-group mb-3 col-md-4">
                                <label for="id_precio">Precio</label>
                                {{ form.precio|add_class:"form-control" }}
                            </div>

                            <!-- Estado Activo/Inactivo -->
                            <div class="form-check-status mb-3 col-md-2">
                                {{ form.status|add_class:"form-check-input" }}
                                <label for="id_status" class="form-check-label">Activo</label>
                            </div>

                        </div>



                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-6">
                                <!-- Descripción -->
                                <div class="form-group mb-3">
                                    <label for="id_descripcion">Descripción</label>
                                    {{ form.descripcion|add_class:"form-control" }}
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>



                        <div class="row text-center">
                            <div class="col md-4"></div>
                            <div class="col md-4">
                                <!-- Imagen con previsualización -->
                                <div class="form-group mb-3">
                                    <label for="id_imagen" class="form-label">Imagen</label>
                                    {{ form.imagen|add_class:"form-control" }}

                                    <!-- Previsualización de la imagen -->
                                    <div class="mt-3 text-center">
                                        <div class="image-preview-container">
                                            <img id="preview-image"
                                                src="{% if form.instance.imagen %}{{ form.instance.imagen.url }}{% else %}{% static 'images/default-image.jpg' %}{% endif %}"
                                                alt="Imagen seleccionada" class="img-fluid rounded shadow-sm"
                                                style="max-width: 100%; max-height: 300px; border-radius: 30px;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col md-4"></div>
                        </div>



                    </form>
                </div>
            </div>
        </div>
    </div>


</div>

<script>
    // Script para mostrar la previsualización de la imagen
    document.getElementById('id_imagen').addEventListener('change', function (event) {
        const previewImage = document.getElementById('preview-image');
        const file = event.target.files[0];
        if (file) {
            previewImage.src = URL.createObjectURL(file);
            previewImage.style.display = "block";
        }
    });
</script>
{% endblock %}

cafeteria/templates/productos/index.html
{# templates/product_cards.html #}
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Lista de Productos</h1>
    <a href="{% url 'producto_create' %}" class="btn  mb-4" style="background-color: #b58450; color: white;">Nuevo Producto</a>

    <div class="row">
        {% for producto in productos %}

        <div class="col-md-4 mb-4">
            <div class="product-card">
                <span class="badge {% if producto.status %}bg-success{% else %}bg-danger{% endif %}">
                    {% if producto.status %}Activo{% else %}Inactivo{% endif %}
                </span>
                <img src="{{ producto.imagen.url }}" class="card-img-top" alt="{{ producto.nombre }}" style="height: 200px; object-fit: cover;">

                
                <h3>{{ producto.nombre }}</h3>
                    <p class="card-text">Precio: ${{ producto.precio }}</p>
                    
                    
                    <div class="d-flex justify-content-between">
                        
                        <a href="{% url 'producto_detail' producto.pk %}" class="btn  btn-sm" style="background-color: #d6a167; color: white;">Ver</a>
                        <a href="{% url 'producto_update' producto.pk %}" class="btn btn-sm" style="background-color: #b58450; color: white;">Editar</a>
                        
                    </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

cafeteria/templates/productos/view.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow-sm mx-auto" style="max-width: 600px;">
        <div class="card-header text-white text-center" style="background-color: #d6a167;">
            <h2>{{ producto.nombre|upper }}</h2>
        </div>
        <div class="card-body">
            <!-- Imagen del Producto -->
            <div class="text-center mb-4">
                <img src="{% if producto.imagen %}{{ producto.imagen.url }}{% else %}{% static 'images/default-image.jpg' %}{% endif %}"
                     alt="{{ producto.nombre }}"
                     class="img-fluid rounded"
                     style="max-width: 100%; max-height: 300px; object-fit: cover;">
            </div>

            <!-- Detalles del Producto -->
            <h5 class="text-muted mb-3">Descripción</h5>
            <p>{{ producto.descripcion }}</p>

            <div class="d-flex justify-content-between align-items-center mt-4">
                <h4 class="text-primary" style="color: #b58450;">Precio: ${{ producto.precio }}</h4>
                <span class="badge {% if producto.status %}bg-success{% else %}bg-danger{% endif %}">
                    {% if producto.status %}Activo{% else %}Inactivo{% endif %}
                </span>
            </div>

            <!-- Acciones -->
            <div class="mt-4 text-center">
                <a href="{% url 'producto_update' producto.pk %}" class="btn mx-2" style="background-color: #d6a167; color: white;">Editar</a>
                
                <a href="{% url 'producto_list' %}" class="btn btn-secondary mx-2">Volver a la lista</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}